import type { Locale } from './localization';

export const ui = {
  zh: {
    view: '查看',
    copy: '复制',
    copied: '已复制',
    copyPrompt: '复制提示词',
    promptCopied: 'Prompt 已复制',
    copyFailed: '复制失败',
    resourceMetadata: '资源元数据',
    tags: '标签',
    overview: '这个提示词能做什么',
    useWhen: '适合谁使用',
    prompt: '提示词',
    promptWorkflow: 'Prompt 工作流',
    sourceFile: '来源文件',
    inputFormat: '输入格式',
    outputFormat: '输出格式',
    knownLimits: '已知限制',
    metadata: '基本信息',
    source: '来源',
    license: '许可证',
    contributor: '贡献者',
    models: '模型',
    tasks: '任务',
    domains: '领域',
    workflowSteps: '逐项检查 Prompt',
    skillWorkflow: 'Skill 工作流',
    supportedTools: '支持工具',
    agentInstruction: '代理工作流指令',
    copyInstruction: '复制工作流指令',
    instructionCopied: '工作流指令已复制',
    copyStepPrompt: '复制这个检查 Prompt',
    stepPromptCopied: '检查 Prompt 已复制',
    recommenderTitle: '选择你现在要做的事',
    recommenderDescription: '三个资源分别对应投稿前模拟审稿、逐项论文质检和 Rebuttal 简报。',
    role: '角色',
    task: '任务',
    domain: '领域',
    open: '打开',
    chosenPrompt: '推荐资源',
    fixedDomain: '领域：人工智能',
  },
  en: {
    view: 'View',
    copy: 'Copy',
    copied: 'Copied',
    copyPrompt: 'Copy Prompt',
    promptCopied: 'Prompt Copied',
    copyFailed: 'Copy failed',
    resourceMetadata: 'Resource metadata',
    tags: 'Tags',
    overview: 'Overview',
    useWhen: 'Use When',
    prompt: 'Prompt',
    promptWorkflow: 'Prompt Workflow',
    sourceFile: 'Source File',
    inputFormat: 'Input Format',
    outputFormat: 'Output Format',
    knownLimits: 'Known Limits',
    metadata: 'Metadata',
    source: 'Source',
    license: 'License',
    contributor: 'Contributor',
    models: 'Models',
    tasks: 'Tasks',
    domains: 'Domains',
    workflowSteps: 'Checkpoint Prompts',
    skillWorkflow: 'Skill Workflow',
    supportedTools: 'Supported Tools',
    agentInstruction: 'Agent Workflow Instruction',
    copyInstruction: 'Copy Workflow Instruction',
    instructionCopied: 'Workflow Instruction Copied',
    copyStepPrompt: 'Copy This Checkpoint Prompt',
    stepPromptCopied: 'Checkpoint Prompt Copied',
    recommenderTitle: 'Choose What You Need Now',
    recommenderDescription:
      'The three resources cover pre-submission reviewer simulation, multi-pass paper checks, and rebuttal briefing.',
    role: 'Role',
    task: 'Task',
    domain: 'Domain',
    open: 'Open',
    chosenPrompt: 'Recommended Resource',
    fixedDomain: 'Domain: Artificial Intelligence',
  },
} satisfies Record<Locale, Record<string, string>>;

export function t(locale: Locale) {
  return ui[locale];
}
