import type { Locale } from './localization';

export const ui = {
  zh: {
    view: '查看',
    copy: '复制',
    copied: '已复制',
    copyPrompt: '复制提示词',
    promptCopied: 'Prompt 已复制',
    copyFailed: '复制失败',
    resourceMetadata: '资源元数据',
    tags: '标签',
    overview: '这个提示词能做什么',
    useWhen: '适合谁使用',
    prompt: '提示词',
    inputFormat: '输入格式',
    outputFormat: '输出格式',
    knownLimits: '已知限制',
    metadata: '基本信息',
    source: '来源',
    license: '许可证',
    contributor: '贡献者',
    models: '模型',
    tasks: '任务',
    domains: '领域',
    recommenderTitle: '两步找到可复制的提示词',
    recommenderDescription: '选择你的身份和任务，直接复制适合人工智能论文场景的提示词。',
    role: '角色',
    task: '任务',
    domain: '领域',
    open: '打开',
    chosenPrompt: '推荐提示词',
    fixedDomain: '领域：人工智能',
  },
  en: {
    view: 'View',
    copy: 'Copy',
    copied: 'Copied',
    copyPrompt: 'Copy Prompt',
    promptCopied: 'Prompt Copied',
    copyFailed: 'Copy failed',
    resourceMetadata: 'Resource metadata',
    tags: 'Tags',
    overview: 'Overview',
    useWhen: 'Use When',
    prompt: 'Prompt',
    inputFormat: 'Input Format',
    outputFormat: 'Output Format',
    knownLimits: 'Known Limits',
    metadata: 'Metadata',
    source: 'Source',
    license: 'License',
    contributor: 'Contributor',
    models: 'Models',
    tasks: 'Tasks',
    domains: 'Domains',
    recommenderTitle: 'Find a copy-ready prompt in two steps',
    recommenderDescription:
      'Choose your role and task, then copy the prompt for an AI paper review scenario.',
    role: 'Role',
    task: 'Task',
    domain: 'Domain',
    open: 'Open',
    chosenPrompt: 'Recommended Prompt',
    fixedDomain: 'Domain: Artificial Intelligence',
  },
} satisfies Record<Locale, Record<string, string>>;

export function t(locale: Locale) {
  return ui[locale];
}
