import type { Locale } from './localization';

export const ui = {
  zh: {
    view: '查看',
    copy: '复制',
    copied: '已复制',
    copyPrompt: '复制提示词',
    copyInstall: '复制安装命令',
    promptCopied: 'Prompt 已复制',
    copyFailed: '复制失败',
    resourceMetadata: '资源元数据',
    tags: '标签',
    overview: '概览',
    useWhen: '适用场景',
    prompt: '提示词',
    inputFormat: '输入格式',
    outputFormat: '输出格式',
    knownLimits: '已知限制',
    metadata: '元数据',
    source: '来源',
    license: '许可证',
    contributor: '贡献者',
    models: '模型',
    skillReady: 'Skill 就绪',
    yes: '是',
    no: '否',
    workflowGoal: '流程目标',
    steps: '步骤',
    expectedOutputs: '预期产物',
    recommendedPrompts: '推荐提示词',
    availableSkill: '可用 Skill',
    skillOverview: 'Skill 概览',
    installForCodex: '安装到 Codex',
    installForClaude: '安装到 Claude Code',
    copyCodexInstall: '复制 Codex 安装命令',
    copyClaudeInstall: '复制 Claude 安装命令',
    skillPreview: 'SKILL.md 预览',
    version: '版本',
    scripts: '脚本',
    included: '包含',
    noScripts: '无脚本',
    tasks: '任务',
    domains: '领域',
    recommenderTitle: '找到合适的审稿流程',
    recommenderDescription: '选择审稿场景，获得工作流、提示词和 Skill 推荐。',
    role: '角色',
    task: '任务',
    stage: '阶段',
    domain: '领域',
    workflow: '工作流',
    skill: 'Skill',
    open: '打开',
  },
  en: {
    view: 'View',
    copy: 'Copy',
    copied: 'Copied',
    copyPrompt: 'Copy Prompt',
    copyInstall: 'Copy Install',
    promptCopied: 'Prompt Copied',
    copyFailed: 'Copy failed',
    resourceMetadata: 'Resource metadata',
    tags: 'Tags',
    overview: 'Overview',
    useWhen: 'Use When',
    prompt: 'Prompt',
    inputFormat: 'Input Format',
    outputFormat: 'Output Format',
    knownLimits: 'Known Limits',
    metadata: 'Metadata',
    source: 'Source',
    license: 'License',
    contributor: 'Contributor',
    models: 'Models',
    skillReady: 'Skill ready',
    yes: 'Yes',
    no: 'No',
    workflowGoal: 'Workflow Goal',
    steps: 'Steps',
    expectedOutputs: 'Expected Outputs',
    recommendedPrompts: 'Recommended Prompts',
    availableSkill: 'Available Skill',
    skillOverview: 'Skill Overview',
    installForCodex: 'Install for Codex',
    installForClaude: 'Install for Claude Code',
    copyCodexInstall: 'Copy Codex Install',
    copyClaudeInstall: 'Copy Claude Install',
    skillPreview: 'SKILL.md Preview',
    version: 'Version',
    scripts: 'Scripts',
    included: 'Included',
    noScripts: 'No scripts',
    tasks: 'Tasks',
    domains: 'Domains',
    recommenderTitle: 'Find the right review workflow',
    recommenderDescription:
      'Select the review situation and get a workflow, prompt, and skill recommendation.',
    role: 'Role',
    task: 'Task',
    stage: 'Stage',
    domain: 'Domain',
    workflow: 'Workflow',
    skill: 'Skill',
    open: 'Open',
  },
} satisfies Record<Locale, Record<string, string>>;

export function t(locale: Locale) {
  return ui[locale];
}
