site:
  name: ReviewPrompt
  site: 'https://piedpiperG.github.io'
  base: '/ReviewPrompt'
  trailingSlash: true

  googleSiteVerificationId: false

metadata:
  title:
    default: ReviewPrompt
    template: '%s | ReviewPrompt'
  description: '面向人工智能论文审稿的双语提示词库。'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: ReviewPrompt
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    cardType: summary_large_image

i18n:
  language: zh-CN
  textDirection: ltr

apps:
  blog:
    isEnabled: false
    postsPerPage: 6

    post:
      isEnabled: false
      permalink: '/%slug%'
      robots:
        index: false

    list:
      isEnabled: false
      pathname: 'blog'
      robots:
        index: false

    category:
      isEnabled: false
      pathname: 'category'
      robots:
        index: false

    tag:
      isEnabled: false
      pathname: 'tag'
      robots:
        index: false

    isRelatedPostsEnabled: false
    relatedPostsCount: 0

analytics:
  vendors:
    googleAnalytics:
      id: null

ui:
  theme: 'light:only'
